import type { TypedFlatConfigItem } from '@antfu/eslint-config'

import preferArrowFunctions from 'eslint-plugin-prefer-arrow-functions'

/** Adds and overrides JavaScript rules defined in @antfu/eslint-config */
export const javascriptConfig: TypedFlatConfigItem = {
  plugins: { 'prefer-arrow-functions': preferArrowFunctions },
  rules: {
    'arrow-body-style': ['error', 'as-needed'],
    complexity: ['error', { max: 12 }],
    'consistent-this': 'error',
    curly: ['error', 'all'],
    'default-case': 'error',
    'default-param-last': 'error',
    'for-direction': 'error',
    'grouped-accessor-pairs': 'error',
    'id-length': ['error', { exceptions: ['t'] }],
    'logical-assignment-operators': [
      'error',
      'always',
      { enforceForIfStatements: true },
    ],
    'max-depth': ['error', 2],
    'max-lines': 'error',
    'new-cap': ['error', { capIsNew: false, newIsCap: true, properties: true }],
    'no-bitwise': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-constructor-return': 'error',
    'no-empty-function': 'error',
    'no-empty-static-block': 'error',
    'no-implicit-coercion': ['error', { disallowTemplateShorthand: true }],
    'no-inner-declarations': 'error',
    'no-invalid-this': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': [
      'error',
      {
        enforceConst: true,
        ignore: [0, 1],
        ignoreClassFieldInitialValues: true,
        ignoreDefaultValues: true,
      },
    ],
    'no-object-constructor': 'error',
    'no-param-reassign': [
      'error',
      {
        ignorePropertyModificationsFor: [
          'accumulator',
          'ctx',
          'context',
          'req',
          'request',
          'res',
          'response',
          '$scope',
          'staticContext',
          'ref',
          'model',
        ],
        ignorePropertyModificationsForRegex: ['^.*(?:Ref|Model)$'],
        props: true,
      },
    ],
    'no-plusplus': 'error',
    'no-promise-executor-return': 'error',
    // TODO запретить использование else
    'no-return-assign': 'error',
    'no-script-url': 'error',
    'no-sequences': 'error',
    'no-shadow': 'error',
    'no-unused-private-class-members': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-void': ['error', { allowAsStatement: true }],
    'operator-assignment': 'error',
    'prefer-arrow-functions/prefer-arrow-functions': 'error',
    'prefer-destructuring': [
      'error',
      { array: true, object: true },
      { enforceForRenamedProperties: true },
    ],
    'prefer-object-spread': 'error',
    'require-atomic-updates': 'error',
    'require-await': 'error',
    // Заменяется параметром 'unusedLocals' в tsconfig
    'unused-imports/no-unused-vars': 'off',
  },
}
