import type { TFlatConfigItem, TPresetMap } from './utils/presets'

import { Preset } from './utils/presets'

/** Auto-fixable: rules with ESLint autofix support. */
const autoFixableRules: TFlatConfigItem['rules'] = {
  'vue/attribute-hyphenation': ['error', 'never'],
  'vue/attributes-order': ['error', { alphabetical: true }],
  'vue/block-order': ['error', { order: ['script', 'template', 'style'] }],
  'vue/component-name-in-template-casing': ['error', 'PascalCase'],
  'vue/component-options-name-casing': ['error', 'PascalCase'],
  'vue/dot-location': ['error', 'property'],
  'vue/html-self-closing': ['error', { html: { void: 'always' } }],
  'vue/max-attributes-per-line': 'off',
  'vue/multi-word-component-names': 'off',
  'vue/no-deprecated-data-object-declaration': 'error',
  'vue/no-deprecated-destroyed-lifecycle': 'error',
  'vue/no-deprecated-dollar-scopedslots-api': 'error',
  'vue/no-deprecated-scope-attribute': 'error',
  'vue/no-deprecated-slot-attribute': 'error',
  'vue/no-deprecated-slot-scope-attribute': 'error',
  'vue/no-deprecated-v-bind-sync': 'error',
  'vue/no-deprecated-v-on-number-modifiers': 'error',
  'vue/no-empty-component-block': 'error',
  'vue/no-implicit-coercion': 'error',
  'vue/no-import-compiler-macros': 'error',
  'vue/no-ref-as-operand': 'error',
  'vue/no-setup-props-reactivity-loss': 'off',
  'vue/no-useless-mustaches': 'error',
  'vue/no-useless-v-bind': 'error',
  'vue/no-v-html': 'off',
  'vue/object-shorthand': [
    'error',
    'always',
    { avoidQuotes: true, ignoreConstructors: false },
  ],
  'vue/padding-line-between-blocks': ['error', 'always'],
  'vue/prefer-import-from-vue': 'error',
  'vue/prefer-separate-static-class': 'error',
  'vue/prefer-template': 'error',
  'vue/require-default-prop': 'off',
  'vue/require-prop-types': 'off',
  'vue/space-infix-ops': 'error',
  'vue/space-unary-ops': ['error', { nonwords: false, words: true }],
  'vue/this-in-template': 'error',
  'vue/v-bind-style': ['error', 'shorthand', { sameNameShorthand: 'always' }],
  'vue/v-for-delimiter-style': ['error', 'of'],
  'vue/v-if-else-key': 'error',
  'vue/v-on-event-hyphenation': ['error', 'never', { autofix: true }],
  'vue/v-on-style': 'error',
  'vue/v-slot-style': [
    'error',
    {
      atComponent: 'v-slot',
      default: 'v-slot',
      named: 'longform',
    },
  ],
  'vue/valid-next-tick': 'error',
}

/** Recommended: mechanical non-autofixable rules for permanent analysis. */
const recommendedRules: TFlatConfigItem['rules'] = {
  'vue/block-lang': ['error', { script: { lang: 'ts' } }],
  'vue/comment-directive': ['error', { reportUnusedDisableDirectives: true }],
  'vue/define-macros-order': [
    'error',
    {
      defineExposeLast: true,
      order: [
        'defineOptions',
        'defineModel',
        'defineProps',
        'defineEmits',
        'defineSlots',
      ],
    },
  ],
  'vue/define-props-declaration': 'error',
  'vue/define-props-destructuring': 'error',
  'vue/html-comment-content-spacing': [
    'error',
    'always',
    { exceptions: ['-'] },
  ],
  'vue/jsx-uses-vars': 'error',
  'vue/no-deprecated-delete-set': 'error',
  'vue/no-deprecated-dollar-listeners-api': 'error',
  'vue/no-deprecated-events-api': 'error',
  'vue/no-deprecated-filter': 'error',
  'vue/no-deprecated-functional-template': 'error',
  'vue/no-deprecated-html-element-is': 'error',
  'vue/no-deprecated-inline-template': 'error',
  'vue/no-deprecated-model-definition': 'error',
  'vue/no-deprecated-props-default-this': 'error',
  'vue/no-deprecated-router-link-tag-prop': 'error',
  'vue/no-deprecated-v-is': 'error',
  'vue/no-deprecated-v-on-native-modifier': 'error',
  'vue/no-deprecated-vue-config-keycodes': 'error',
  'vue/no-dupe-keys': 'error',
  'vue/no-dupe-v-else-if': 'error',
  'vue/no-duplicate-attributes': 'error',
  'vue/no-empty-pattern': 'error',
  'vue/no-export-in-script-setup': 'error',
  'vue/no-irregular-whitespace': 'error',
  'vue/no-lone-template': 'error',
  'vue/no-loss-of-precision': 'error',
  'vue/no-multiple-objects-in-class': 'error',
  'vue/no-multiple-slot-args': 'error',
  'vue/no-parsing-error': 'error',
  'vue/no-reserved-component-names': 'error',
  'vue/no-reserved-keys': 'error',
  'vue/no-reserved-props': 'error',
  'vue/no-restricted-v-bind': ['error', '/^v-/'],
  'vue/no-template-key': 'error',
  'vue/no-textarea-mustache': 'error',
  'vue/no-useless-template-attributes': 'error',
  'vue/no-v-for-template-key-on-child': 'error',
  'vue/prefer-true-attribute-shorthand': 'error',
  'vue/require-component-is': 'error',
  'vue/require-macro-variable-name': 'error',
  'vue/require-render-return': 'error',
  'vue/require-slots-as-functions': 'error',
  'vue/require-toggle-inside-transition': 'error',
  'vue/return-in-computed-property': 'error',
  'vue/return-in-emits-validator': 'error',
  'vue/valid-attribute-name': 'error',
  'vue/valid-define-emits': 'error',
  'vue/valid-define-options': 'error',
  'vue/valid-define-props': 'error',
  'vue/valid-template-root': 'error',
  'vue/valid-v-bind': 'error',
  'vue/valid-v-cloak': 'error',
  'vue/valid-v-else': 'error',
  'vue/valid-v-else-if': 'error',
  'vue/valid-v-for': 'error',
  'vue/valid-v-html': 'error',
  'vue/valid-v-if': 'error',
  'vue/valid-v-is': 'error',
  'vue/valid-v-memo': 'error',
  'vue/valid-v-model': 'error',
  'vue/valid-v-on': 'error',
  'vue/valid-v-once': 'error',
  'vue/valid-v-pre': 'error',
  'vue/valid-v-show': 'error',
  'vue/valid-v-slot': 'error',
  'vue/valid-v-text': 'error',
}

/** Vue rules by preset. */
export const vueConfig: TPresetMap = {
  [Preset.AUTO_FIXABLE]: { rules: autoFixableRules },
  [Preset.RECOMMENDED]: { rules: recommendedRules },
}
